name: smiles-rnn
channels:
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - cudatoolkit=10.2.89
  - jedi=0.18.0
  - numpy=1.21.2
  - numpy-base=1.21.2
  - pandas=1.3.3
  - python=3.9.2
  - pytorch=1.8.1
  - rdkit=2021.03.1
  - setuptools=58.2.0
  - tensorboard=2.4.1
  - torchaudio=0.8.1
  - torchvision=0.9.1
  - tornado=6.1
  - tqdm=4.60.0
  - wheel=0.37.0
  - pip=21.3
  - pip:
    - deepsmiles==1.0.1
    - google-auth==1.35.0
    - selfies==1.0.4
    - promptsmiles
